version: '3.9'

services:
  database_insta_api:
    image: postgres
    container_name: database_insta_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=insta
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local